# Generated by Django 3.1.2 on 2020-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(default=0)),
                ('name', models.CharField(default='no name', max_length=128)),
                ('eff', models.TextField(blank=True, default='no effect', null=True)),
            ],
        ),
    ]
