# Generated by Django 3.1.2 on 2020-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('cards_pattern', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='eff',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
